# States
UD_STATE = "customer_state"
UD_AGENT_ID = "agent_id"
UD_DYN_FIELD = "dyn_field"
UD_CURRENT_SERVER = "current_server"
UD_CURRENT_PLAN = "current_plan"
UD_CURRENT_ORDER = "current_order"
UD_CURRENT_PAYMENT = "current_payment"
UD_CURRENT_TICKET = "current_ticket"
UD_BUY_GB = "buy_gb"
UD_BUY_MONTHS = "buy_months"
UD_BUY_SERVER_ID = "buy_server_id"
UD_BUY_PLAN_ID = "buy_plan_id"
UD_TICKET_QUESTION = "ticket_question"
UD_TICKET_MODE = "ticket_mode"
UD_WIZARD_GB = "wizard_gb"
UD_WIZARD_MONTHS = "wizard_months"

STATE_START = "start"
STATE_CANCEL = "cancel"
STATE_BUY_WAITING = "buy_waiting"
STATE_RECEIPT_WAITING = "receipt_waiting"
STATE_CARD_LAST4 = "card_last4"
STATE_TICKET_NEW = "ticket_new"
STATE_TICKET_REPLY = "ticket_reply"
STATE_TICKET_WAITING_TEXT = "ticket_waiting_text"
STATE_TICKET_WAITING_TITLE = "ticket_waiting_title"
STATE_TICKET_WAITING_PHOTO = "ticket_waiting_photo"
STATE_TICKET_CONFIRM = "ticket_confirm"
STATE_RENAME_WAITING = "rename_waiting"
STATE_REPLACE_LINK_WAITING = "replace_link_waiting"
STATE_ZARINPAL_WAITING = "zarinpal_waiting"
STATE_PERFECT_MONEY_WAITING = "perfect_money_waiting"
STATE_CRYPTO_WAITING = "crypto_waiting"
STATE_COUPON_WAITING = "coupon_waiting"
STATE_CONNECT_WAITING = "connect_waiting"
STATE_TRIAL_WAITING_NAME = "trial_waiting_name"
STATE_AGENT_MSG_WAITING = "agent_msg_waiting"

# Callback prefixes
CB_BUY_LOC = "buy:loc:"
CB_BUY_CAT = "buy:cat:"
CB_BUY_PLAN = "buy:plan:"
CB_BUY_CONFIRM = "buy:confirm:"
CB_BUY_CONFIRM_DYN = "buy:confirm_dyn:"
CB_BUY_PAY_DIRECT = "buy:pay_direct:"
CB_BUY_BACK_MAIN = "buy:back_main"
CB_BUY_EXIT_MAIN = "buy:exit_main"
CB_BUY_MIXED_FIXED = "buy:mixed:fixed:"
CB_BUY_MIXED_DYN = "buy:mixed:dyn:"

CB_WIZ_GB_INC = "wiz:gb_inc"
CB_WIZ_GB_DEC = "wiz:gb_dec"
CB_WIZ_MONTH_INC = "wiz:month_inc"
CB_WIZ_MONTH_DEC = "wiz:month_dec"
CB_WIZ_SHOW_FIXED = "wiz:show_fixed"

CB_STATUS_LIST = "status:list:"
CB_STATUS_CONFIGS = "status:configs:"
CB_STATUS_RENEW = "status:renew:"
CB_STATUS_RENAME = "status:rename:"
CB_STATUS_REPLACE_LINK = "status:replace_link:"
CB_STATUS_DETACH = "status:detach:"
CB_STATUS_DIRECT = "status:direct:"
CB_STATUS_SUB_LINK = "status:sub_link:"
CB_STATUS_AUTO_SUB = "status:auto_sub:"
CB_STATUS_SUB_B64 = "status:sub_b64:"
CB_STATUS_MULTI = "status:multi:"
CB_STATUS_MULTI_B64 = "status:multi_b64:"
CB_STATUS_DIRECTCFG = "status:directcfg:"
CB_STATUS_REFRESH = "status:refresh:"
CB_STATUS_GUIDE = "status:guide:"
CB_STATUS_MENU = "status:menu:"
CB_STATUS_LIST_BACK = "status:list_back"

CB_RENEW_SVC = "renew:svc:"
CB_RENEW_BACK = "renew:back:"

CB_PAY_RECEIPT_DONE = "pay:receipt_done"
CB_PAY_CANCEL = "pay:cancel"

CB_SUPPORT_FAQ = "support:faq"
CB_SUPPORT_MY = "support:my:"
CB_SUPPORT_NEW = "support:new"
CB_SUPPORT_VIEW = "support:view:"
CB_SUPPORT_REPLY = "support:reply:"
CB_SUPPORT_CLOSE = "support:close:"
CB_SUPPORT_BACK_MAIN = "support:back_main"
CB_SUPPORT_MENU = "support:menu"
CB_SUPPORT_SKIP = "support:skip"
CB_SUPPORT_SEND = "support:send"
CB_SUPPORT_EDIT = "support:edit"
CB_SUPPORT_CANCEL = "support:cancel"

CB_TRIAL_LOC = "trial:loc:"
CB_TRIAL_BACK = "trial:back"

CB_GUIDE_ANDROID = "guide:android:"
CB_GUIDE_IOS = "guide:ios:"
CB_GUIDE_WINDOWS = "guide:windows:"
CB_GUIDE_MAC = "guide:mac:"
CB_GUIDE_LINUX = "guide:linux:"
CB_GUIDE_BACK = "guide:back:"

CB_FORCEJOIN_CHECK = "forcejoin:check"

# AgentBot -> CustomerBot direct message reply
CB_AGENT_MSG_REPLY = "agmsg:reply"

# AgentBot -> CustomerBot communication
AGENT_BOT_WALLET = "customer_wallet"
AGENT_BOT_BALANCE = "customer_balance"

# Keyboard texts
BTN_STATUS = "📊وضعیت اشتراک"
BTN_RENEW = "♾تمدید اشتراک"
BTN_BUY = "💳خرید اشتراک"
BTN_CONNECT = "🔗اتصال اشتراک"
BTN_TRIAL = "🔥تست رایگان"
BTN_SUPPORT = "📩پشتیبانی"
BTN_GUIDE = "📚راهنما"
BTN_FAQ = "❗️سوالات متداول"
BTN_BACK = "بازگشت"
BTN_PAY_DONE = "✅ پرداخت کردم، ارسال رسید"

# Rate limiting
ACTION_COOLDOWN = 2
BUY_COOLDOWN = 60
