plugins {
    id "com.android.application"
}

android {
    namespace "com.hiddifysellbot.smsverifier"
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.hiddifysellbot.smsverifier"
        minSdk 23
        targetSdk 35
        versionCode 7
        versionName "1.1.5"
    }
}
