CALLBACK_PREFIX = "agbot:"

MENU_MAIN = "menu"
MENU_SUBSCRIPTIONS = "subs"
MENU_WALLET = "wallet"
MENU_PLANS = "plans"
MENU_CUSTOMER_BOT = "cbot"
MENU_TICKETS = "tickets"
MENU_SETTINGS = "settings"

SUBS_CREATE = "subs:create"
SUBS_SEARCH = "subs:search"
SUBS_EXPIRED = "subs:expired"
SUBS_DETAIL = "subs:detail"
SUBS_BACK = "subs:back"
SUBS_CFG = "subs:cfg"
SUBS_RENEW = "subs:renew"
SUBS_DISABLE = "subs:disable"
SUBS_ENABLE = "subs:enable"
SUBS_DELETE = "subs:delete"
SUBS_DODELETE = "subs:dodelete"
SUBS_NEWLINK = "subs:newlink"

WALLET_VIEW = "wallet:view"
WALLET_CREATE = "wallet:create"
WALLET_BACK = "wallet:back"

PLANS_MODE = "plans:mode"
PLANS_DYNAMIC_SETTINGS = "plans:dynset"
PLANS_BACK = "plans:back"

CBOT_ACTIVATE = "cbot:activate"
CBOT_TOKEN = "cbot:token"
CBOT_BACK = "cbot:back"

TICKET_PENDING = "ticket:pending"
TICKET_OPEN = "ticket:open"
TICKET_CLOSED = "ticket:closed"
TICKET_VIEW = "ticket:view"
TICKET_REPLY = "ticket:reply"
TICKET_CLOSE = "ticket:close"
TICKET_BACK = "ticket:back"

SETTINGS_USERS = "set:users"
SETTINGS_ORDERS = "set:orders"
SETTINGS_TRANSACTIONS = "set:tx"
SETTINGS_GIFTS = "set:gifts"
SETTINGS_BROADCAST = "set:broadcast"
SETTINGS_CONFIG = "set:config"
SETTINGS_BACK = "set:back"

SET_USERS_LIST = "set:users:list"
SET_USERS_SEARCH = "set:users:search"
SET_USERS_BACK = "set:users:back"

SET_ORDERS_LIST = "set:orders:list"
SET_ORDERS_SEARCH = "set:orders:search"
SET_ORDERS_BACK = "set:orders:back"

SET_TX_APPROVED = "set:tx:approved"
SET_TX_REJECTED = "set:tx:rejected"
SET_TX_PENDING = "set:tx:pending"
SET_TX_CARD = "set:tx:card"
SET_TX_SEARCH = "set:tx:search"
SET_TX_BACK = "set:tx:back"

SET_GIFTS_BACK = "set:gifts:back"

SET_CFG_SHOP = "set:cfg:shop"
SET_CFG_PAYMENT = "set:cfg:payment"
SET_CFG_BACK = "set:cfg:back"

SHOP_BUY_TOGGLE = "shop:buy"
SHOP_RENEW_TOGGLE = "shop:renew"
SHOP_BACK = "shop:back"

PAY_CARD_TOGGLE = "pay:card"
PAY_LAST4_TOGGLE = "pay:last4"
PAY_RANDOM_TX = "pay:randtx"
PAY_SMS_AUTO = "pay:smsauto"
PAY_CARDS_LIST = "pay:cards"
PAY_CARD_ADD = "pay:cardadd"

UD_AGENT_ID = "agent_id"
UD_AGENT_DATA = "agent_data"
UD_STATE = "state"

STATE_BROADCAST_MESSAGE = "st:broadcast_message"
PAY_CARD_EDIT = "pay:cardedit"
PAY_CARD_DEL = "pay:carddel"
PAY_CARD_TEXT = "pay:cardtext"
PAY_BACK = "pay:back"

STATE_ADD_CUSTOMER_TG = "st:addcust_tg"
STATE_ADD_CUSTOMER_NAME = "st:addcust_name"
STATE_CREATE_SERVICE_NAME = "st:createsvc_name"
STATE_WALLET_CREATE = "st:wallet_create"
STATE_SET_SALE_PRICE = "st:sale_price"
STATE_CBOT_TOKEN = "st:cbot_token"
STATE_REPLY_TICKET = "st:reply_ticket"
STATE_REPLY_TICKET_SHOT = "st:reply_ticket_shot"
STATE_REPLY_TICKET_CONFIRM = "st:reply_ticket_confirm"
STATE_ADD_CARD = "st:add_card"
STATE_ADD_CARD_NUMBER = "st:add_card_number"
STATE_ADD_CARD_OWNER = "st:add_card_owner"
STATE_ADD_CARD_BANK = "st:add_card_bank"
STATE_EDIT_CARD = "st:edit_card"
STATE_SET_CARD_TEXT = "st:card_text"
STATE_SEARCH_CUSTOMER = "st:search_cust"
STATE_SEARCH_ORDER = "st:search_order"
STATE_SEARCH_TX = "st:search_tx"
STATE_SEARCH_SERVICE = "st:search_svc"
STATE_SEARCH_NAME = "st:search_name"
STATE_DYNAMIC_SETTINGS = "st:dyn_settings"
STATE_RENEW_DAYS = "st:renew_days"
STATE_RENEW_GB = "st:renew_gb"
STATE_SERVICE_NAME = "st:service_name"
UD_PAGE = "page"
UD_SELECTED_SERVER = "sel_server"
UD_SELECTED_PLAN = "sel_plan"
UD_SELECTED_CUSTOMER = "sel_customer"
UD_SELECTED_SERVICE = "sel_service"
UD_SELECTED_TICKET = "sel_ticket"
UD_SELECTED_CARD = "sel_card"
UD_DYN_FIELD = "dyn_field"
UD_FIXED_NEW_PLAN = "fixed_new_plan"
UD_FIXED_CAT_ID = "fixed_cat_id"

STATE_DYN_EDIT_FIELD = "st:dyn_edit_field"
STATE_FIXED_ADD_CAT_TITLE = "st:fixed_add_cat_title"
STATE_FIXED_EDIT_CAT_TITLE = "st:fixed_edit_cat_title"
STATE_FIXED_ADD_PLAN_TITLE = "st:fixed_add_plan_title"
STATE_FIXED_ADD_PLAN_GB = "st:fixed_add_plan_gb"
STATE_FIXED_ADD_PLAN_DAYS = "st:fixed_add_plan_days"
STATE_FIXED_ADD_PLAN_PRICE = "st:fixed_add_plan_price"
